#!/command/with-contenv bash
# shellcheck shell=bash

set -eu

. /usr/local/bin/backend-functions

log "Starting user initialization"

if [ "$(id -g nordvpn)" -ne "$PGID" ]; then
    log "Updating nordvpn group ID from $(id -g nordvpn) to $PGID"
    groupmod --non-unique --gid "$PGID" nordvpn
fi

if [ "$(id -u nordvpn)" -ne "$PUID" ]; then
    log "Updating nordvpn user ID from $(id -u nordvpn) to $PUID"
    usermod --non-unique --uid "$PUID" nordvpn
fi

log "User initialization completed"
exit 0
