#!/command/with-contenv bash
# shellcheck shell=bash

set -eu

. /usr/local/bin/backend-functions

SCRIPT_NAME="SERVICE-NORDVPN"

log "Stopping NordVPN service"

log "Cleaning up VPN firewall rules"
run4 -F VPN-SERVER

log "Disconnecting OpenVPN"
echo "signal SIGTERM" | nc -U "$MGMT_SOCK_FILE"
sleep 5

log "Cleaning up VPN configuration files"
rm -f /run/xt/nordvpn.ovpn

log "NordVPN service stopped"
exit 0
