#!/command/with-contenv bash
# shellcheck shell=bash

set -eu

. /usr/local/bin/backend-functions

log "Initializing firewall"

/usr/local/bin/init-firewall

log "Firewall initialization completed"
exit 0
