#!/command/with-contenv bash
# shellcheck shell=bash

set -eu

. /usr/local/bin/backend-functions

log "Starting authentication setup"

log "Creating VPN authentication file"
echo "$USER" > "$OVPN_AUTH_FILE"
echo "$PASS" >> "$OVPN_AUTH_FILE"
chmod 0600 "$OVPN_AUTH_FILE"
chown nordvpn:nordvpn "$OVPN_AUTH_FILE"

log "Authentication setup completed"
exit 0
